---
parserOptions:
  parser: babel-eslint

extends:
  - airbnb-base
  - plugin:vue/recommended

settings:
  import/resolver:
    webpack:
      config: ./.electron-vue/webpack.renderer.config.js

rules:
  import/extensions:
    - error
    - on
    - js: off
      vue: off

  indent: off
  indent-legacy:
    - error
    - tab

  no-tabs: off
  max-len:
    - warn
    - 120

  no-undef: error
  no-unused-vars: error

  # Possible Errors
  vue/no-dupe-keys: error
  vue/no-reserved-keys: error
  vue/no-shared-component-data: error
  vue/no-unused-vars: error

  vue/require-valid-default-prop: error
  vue/return-in-computed-property: error


  # Best Practices
  vue/no-duplicate-attributes: error
  vue/no-side-effects-in-computed-properties: error
  vue/order-in-components: error

  # Stylistic Issues
  vue/attribute-hyphenation: error
  vue/html-indent:
    - error
    - tab
  vue/html-quotes: error
  vue/html-self-closing:
    - error
    - html:
        normal: always
        void: always
        component: always
  vue/max-attributes-per-line: error
  vue/mustache-interpolation-spacing: error
  vue/name-property-casing:
    - error
    - PascalCase
  vue/no-multi-spaces: error
  vue/v-bind-style: error
  vue/v-on-style: error
